# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: Ceara Byrne
title: Crash & Byrne
subtitle: The trials and tribulations of completing ones dissertation.
email: ceara.byrne@gatech.edu
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the documentation of my dissertation. I conduct both research in Animal Computer Interaction and in Brain Computer Interfaces. You might ask...what do these have in common?
My original answer was that my advisor is the commonality, but you know what, BCI is pretty freaking cool and I am pretty excited about it. And then you might say...but ceara, this sounds like you 
are attemtping multiple dissertations at once. Originally, it was pretty daunting, but research is research and once you have the processes down, it does not take a whole lot to pick up a new 
field and move forward in that direction...especially once you start to get really excited about this new field.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "@thenanoestkiwi"
github_username:  rawrious

show_downloads: true
google_analytics:
theme: jekyll-theme-midnight

# Build settings
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
